halo/default/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auther
from default import views


urlpatterns = [
     path('', views.landing, name='landing'),
     path('rules/', views.rules, name='rules'),
     path('coming-soon', views.waitlist, name='waitlist'),
    #  path('register', views.registration, name='registration'),
     path('login', views.login_page, name='login'),
     path('logout/', views.logout_user, name='logout'),

     path('reset-password', views.password_reset_request, name="reset_password"),
     path('reset-password-sent',
          auther.PasswordResetDoneView.as_view(template_name="defaults/password_reset_sent.html"), name='password_reset_done'),
     path('reset/<uidb64>/<token>', auther.PasswordResetConfirmView.as_view(template_name="defaults/password_reset_form.html"),
         name='password_reset_confirm'),
     path('reset-password-success', auther.PasswordResetCompleteView.as_view(template_name="defaults/password_reset_success.html"),
         name='password_reset_complete'),
     path('get/json/email/verification', views.check_email, name="check_email"),
     path('get/json/password/verification', views.check_password, name="check_password"),
     
     path('fundraiser', views.fundraiser_link, name='fundraiser'),
     path('waiver', views.minor_waiver_form, name='minor_waiver'),
     path('profile/<int:pk>', views.profile_page, name='profile'),
     path('privacy/', views.privacy_policy_view, name='privacy'),
     path('conduct/', views.code_of_conduct_view, name='conduct'),
     path('incomingcall', views.incoming_call, name='incomingcall'),

]

halo/halo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from qr_code import urls as qr_code_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
    path('', include('hacker.urls')),
    path('', include('default.urls')),
    path('', include('organizer.urls')),
    path('', include('sponsor.urls')),
    path('', include('teams.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

halo/default/models.py
from atexit import register
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,  PermissionsMixin
from django.core.validators import MaxValueValidator, FileExtensionValidator
from phone_field import PhoneField
from .managers import CustomUserManager
from .choices import *
# Create your models here.
import datetime
from django.utils import timezone


class CustomUser(AbstractBaseUser, PermissionsMixin):

    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    joined_discord = models.BooleanField(default=False)
    is_submitted = models.BooleanField(default=False)

    is_email_verified = models.BooleanField(default=False)
    is_phone_verified = models.BooleanField(default=False)
    phone_verification_code = models.CharField(max_length=6, blank=True, null=True)

    timestamp = models.DateTimeField(null=True, blank=True)

    source = models.TextField(null=True, blank=True, default="")

    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    country_code = models.CharField(default="", max_length=32, blank=False, choices=country_code_choices)
    phone = models.CharField(max_length=15)
    city = models.CharField(
        default="", max_length=75, null=False, blank=False)
    country = models.CharField(
        default="", max_length=60, blank=False, choices=country_choices)
    project_url = models.TextField(null=False, blank=False, max_length=200)
    issue_desc = models.TextField(null=False, blank=False)
    project_info = models.TextField(null=False, blank=False)
    project_impact = models.TextField(null=False, blank=False)
    contribution_url = models.TextField(null=False, blank=False, max_length=200)
    feedback = models.TextField(null=True, blank=True, default="")
    expertise = models.TextField(null=True, blank=True, default="")
    interest = models.TextField(null=True, blank=True, default="")
    team = models.TextField(null=True, blank=True, default="")
    profile_url = models.TextField(null=True, blank=True, max_length=200, default="")
    hackathon = models.TextField(null=True, blank=True, max_length=200, default="")
    coder_password = models.TextField(null=True, blank=True, max_length=200, default="")
    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

class Referer(models.Model):
    
    referer = models.TextField(null=True, blank=True, default="")
    click_source = models.TextField(null=True, blank=True, default="")


class Event(models.Model):

    title = models.CharField(max_length=120, blank=False, null=False)
    description = models.CharField(max_length=200, blank=False, null=False)
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    end_time = models.TimeField(auto_now=False, auto_now_add=False)
    date = models.DateField()

    def __str__(self):
        return self.title + str(self.date) + str(self.start_time) + '-' + str(self.end_time)


class WaitingList(models.Model):

    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    full_name = models.CharField(max_length=64)

    def __str__(self):
        return self.email + ": " + self.full_name


class OtpCode(models.Model):

    otpcode = models.CharField(max_length=6)


class IncomingPhoneNo(models.Model):

    From = models.CharField(max_length=18)
    FromCity = models.CharField(max_length=18)
    FromCountry = models.CharField(max_length=18)
    Caller = models.CharField(max_length=18)
    CallerCity = models.CharField(max_length=18)
    CallerCountry = models.CharField(max_length=18)
    time = models.DateTimeField(default=timezone.now, blank=True)

halo/default/views.py
from email import message
import email
from multiprocessing import context
from django.http.response import HttpResponse
from django.http import JsonResponse
from django.contrib import messages
import json
from django.shortcuts import redirect, render
from .forms import CustomUserCreationForm, HackerCreationForm, WaitingListCreationForm, CustomUserChangeForm
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

from hacker.models import HackerInfo
from organizer.models import OrganizerInfo
from .helper import add_group, decide_redirect, decide_type
from .emailer import *
from .models import WaitingList, CustomUser, Referer
from django.templatetags.static import static

from .decorators import user_not_authenticated

# incoming calls handling twilio
import datetime
from .models import IncomingPhoneNo
from twilio.twiml.voice_response import VoiceResponse
from django.http import HttpResponse

# first time email
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage, EmailMultiAlternatives
from hacker.tokens import account_activate_token


def landing(request):
    source = request.GET.get('source')
    root_url = request.build_absolute_uri('/')[:-1]
    referer = request.META.get('HTTP_REFERER')

    if (referer is not None) or (source != request.session.get('source')):
        if referer is not None:
            if not referer.startswith(root_url):
                referer = Referer(referer=request.META.get('HTTP_REFERER'), click_source=request.GET.get('source'))
                referer.save()
        else:
            referer = Referer(referer=None, click_source=request.GET.get('source'))
            referer.save()

    if source is not None:
        request.session['source'] = source

    context = {}

    return render(request, 'defaults/landing.html', context)


def rules(request):
    return render(request, 'defaults/rules.html')


def privacy_policy_view(request):
    pdf_url = static('pdf/privacy_policy.pdf')
    return redirect(pdf_url)


def code_of_conduct_view(request):
    pdf_url = static('pdf/code_of_conduct.pdf')
    return redirect(pdf_url)


def clean_country_code(country_code):
    start_index = country_code.find('+') + 1
    end_index = country_code.find(')', start_index)
    if start_index != -1 and end_index != -1:
        return country_code[start_index:end_index]
    else:
        return None
    
def waitlist(request):
    # fundraiser_link = request.get_host() + "/fundraiser"
    if request.method == "POST":
        waitlist_create_form = WaitingListCreationForm(request.POST)
        if waitlist_create_form.is_valid():
            waitlist = waitlist_create_form.save()
            new_email = waitlist_create_form.cleaned_data['email']
            new_name = waitlist_create_form.cleaned_data['full_name']
            new_waitlister_added(new_email, new_name)
            messages.success(
                request, "Thanks for joining the waiting list, you will receive an email with more information soon!")
            return redirect('waitlist')
    else:
        waitlist_create_form = WaitingListCreationForm()
    context = {'waitlist_form': waitlist_create_form}
    return render(request, 'defaults/coming-soon.html', context)


@user_not_authenticated
def registration(request):
    if request.method == 'POST':
        create_user_form = CustomUserCreationForm(request.POST, request.FILES)
        create_hacker_form = HackerCreationForm(request.POST)
        if create_hacker_form.is_valid() and create_user_form.is_valid():
            pword = create_user_form.cleaned_data['password1']
            user = create_user_form.save()
            if request.session.get('source') is not None:
                source = request.session.get('source')
                user.source = source
            phone = request.POST.get('phone')
            user.phone = phone
            email = create_user_form.cleaned_data['email'].lower()
            user = create_user_form.save(commit=False)
            user.email = email
            user.save()
            hacker = create_hacker_form.save(commit=False)
            hacker.user = user
            hacker.save()
            add_group(user, 'hacker')
            print()
            user = authenticate(request, username=user.email, password=pword)
            if user is not None:
                login(request, user)
                activate_email(request, user, user.email)
                return redirect('hacker-dash')
        else:
            pass
    else:
        create_user_form = CustomUserCreationForm()
        create_hacker_form = HackerCreationForm()
    context = {'create_hacker_form': create_hacker_form,
               'create_user_form': create_user_form}
    return render(request, 'defaults/register.html', context)


def login_page(request):
    if request.method == "POST":
        email = request.POST.get('email').lower()
        email = "".join(email.split())
        passwrd = request.POST.get('password')
        user = authenticate(request, email=email, password=passwrd)
        if user is not None and decide_type(user) == "hacker":
            user.save()
            login(request, user)
            return redirect('hacker-dash')
        elif user is not None and decide_type(user) == "head-organizer":
            login(request, user)
            return redirect('organizer-dash')
        else:
            messages.error(request, "Username or Password Incorrect")
    context = {}
    return render(request, 'defaults/login.html', context)


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            user_email = password_reset_form.cleaned_data['email'].lower()
            user_obj_valid = CustomUser.objects.filter(
                email=user_email).exists()
            if user_obj_valid:
                user_obj = CustomUser.objects.get(email=user_email)
                uid = urlsafe_base64_encode(force_bytes(user_obj.pk))
                token = default_token_generator.make_token(user_obj)
                password_reset_instructions(
                    request.get_host(), user_obj, uid, token)
                return redirect('password_reset_done')
            else:
                messages.error(request, "Email could not be found!")
    password_reset_form = PasswordResetForm()
    context = {'password_reset_form': password_reset_form}
    return render(request, 'defaults/password_reset.html', context)


def logout_user(request):
    logout(request)
    return redirect('landing')  # TODO


def check_email(request):
    if request.method == "POST":
        body_unicode = request.body.decode('utf-8')
        received_json = json.loads(body_unicode)
        data = received_json.get("data")
        email_value = data.get("email").lower()
        message = ""
        validity = True
        if (CustomUser.objects.filter(email=email_value).exists()):
            message = "This Email is Already Registered"
            validity = False
        data = {
            "valid": validity,
            "message": message
        }
        return JsonResponse(data)
    return JsonResponse({"valid": False}, status=200)


def check_password(request):
    if request.method == "POST":
        body_unicode = request.body.decode('utf-8')
        received_json = json.loads(body_unicode)
        data = received_json.get("data")
        password_value = data.get("p1")
        try:
            validate_password(password_value)
        except ValidationError as e:
            data = {
                "valid": False,
                "errors": list(e)
            }
            return JsonResponse(data)
        data = {
            "valid": True,
            "errors": ""
        }
        return JsonResponse(data)
    return JsonResponse({"valid": False}, status=200)
    return redirect('landing')


def fundraiser_link(request):
    context = {}
    return render(request, 'defaults/fundraiser.html', context)


def minor_waiver_form(request):
    context = {}
    return render(request, 'defaults/minor_waiver.html', context)


def profile_page(request, pk):
    user = None
    try:
        user = CustomUser.objects.get(id=pk)
    except:
        return redirect(decide_redirect(request.user))
    if user != request.user:
        return redirect(decide_redirect(request.user))
    if any("Your Submission Updated!" in message.message for message in messages.get_messages(request)):
        messages.get_messages(request).used = True
    elif user.is_submitted is True:
        messages.info(
                request, "You have already applied for a prize. You can still update your submission before the deadline.")
    else:
        if not user.is_email_verified and not user.is_phone_verified:
            messages.info(
                request, "You can see the submission questions, however you will not be able to submit your answers until your phone number and email are verified!")
        elif not (user.is_email_verified):
            messages.info(
                request, "You can see the submission questions, however you will not be able to submit your answers until your phone number and email are verified!")
        elif not (user.is_phone_verified):
            messages.info(
                request, "You can see the questions now. You will not be able to submit your answers until your phone number is verified!")
        else:
            messages.success(

halo/default/templates/defaults/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Christmas Challenge</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
    {% block head %}

    {% endblock %}
</head>
<body>
    <div class="container">
        {% block content %}
        
        {% endblock %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block script %}

    {% endblock %}

</body>
</html>

halo/default/templates/defaults/form_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="TCNJ's 24-hour Hackathon">
    <meta name="keywords" content="hackathon, TCNJ, 24-hour">
    <meta name="author" content="challenge@parkyeri.com">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/61b96161ad.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/form_css/form.css' %}">
    <script src="{% static 'js/form/form.js' %}" defer></script>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
    {% block head %}
        
    {% endblock head %}
</head>
<body style="height: 100vh; background-image: radial-gradient(rgba(27, 23, 23, 1),rgba(129, 0, 0, 1)); background-repeat: repeat; background-size: cover ">
    
    <div id="width-control" class="container justify-content-center align-items-center w-control" style="height: 100%;width:fit-content;">

		<div class=" p-4 rounded-3 bg-cream text-white " style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
            <div class="container py-3">

				{% block form %}

				{% endblock %}
			</div>
		</div>
	</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/2b86215731.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@1,300&display=swap" rel="stylesheet">

    
    {% block script %}
        
    {% endblock script %}
        
</body>
</html>

halo/default/templates/defaults/password_reset.html
{% extends 'defaults/nav_reset.html' %}

{% load static %}


{% block head %}
<script src="{% static 'js/form/passwordReset.js' %}" defer></script>
<link rel="stylesheet" href="{% static 'css/landing_css/style.css' %}">
<style>
  .btn:hover {
    color: #00873E !important;
    filter: brightness(140%);
  }
</style>
<title> Christmas Challenge Password Reset </title>
{% endblock head %}

{% block form %}
<p id="password_reset" class="d-none"></p>
<h3 class="text-center pb-4 text-dark">Password reset</h3>

<p class="text-center pb-4 text-dark">Forgotten your password? Enter your email address below, and we’ll email
  instructions for setting a new one.</p>
<form method="post">{% csrf_token %}
  <div class="row m-1 w-100 justify-content-center">
    <div class="col text-center">
      {% for message in messages %}
      <div class="alert alert-danger alert-dismissible col-md-3 col-lg-12" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="row m-1 w-100 justify-content-center mb-4">
    <div class="col text-center" id="form_email">
      {{password_reset_form.email}}
    </div>
  </div>
  <div class="row m-1 w-100 justify-content-center">
    <div class="col text-center">
      <button class="btn btn-submit" type="submit" name="Send Email">Submit</button>
    </div>
  </div>
</form>
{% endblock form %}


{% block script %}
<script defer>
  var container, inputs, index;
  container = document.getElementById('form_email');
  inputs = container.getElementsByTagName('input');

  for (index = 0; index < inputs.length; ++index) {
    inputs[index].placeholder = "Email";
    inputs[index].className += "form-control text-center"

  }
</script>
{% endblock script %}

halo/default/templates/defaults/register.html
{% extends 'defaults/form_base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="{% static 'js/register/register.js' %}" defer></script>
<script src="{% static 'js/form/inputRestrictions.js' %}" defer></script>
<style>
	.btn:hover {
		color: #00873E !important;
		filter: brightness(140%);
	}

	.form-contact-link:hover {
		opacity: 0.7;
	}

	.btn:active {
		transform: scale(1.03);
		transition: all 0.1s ease-out;
	}
</style>
<title> Christmas Challenge Register </title>
{% endblock head %}
{% block form %}
<form style="height: 85%" method="POST" enctype="multipart/form-data"> {% csrf_token %}
	<div class="form-whole">
		<!-- 0 : General Information -->
		<div class="form-page">
			<div class="row mb-4">
				<div class="col-12 text-center g-5">
					<h3 class="text-dark">General Information</h3>
				</div>
			</div>
			<div class="row g-3">
				<div class="col-md-6 col-sm-12">
					<div class="form-floating">
						{{create_user_form.first_name}}
						<label class="text-muted" for="id_first_name"> <span class="fw-normal text-dark">First
								Name</span> <span class="text-danger text-bold">*</span> </label>
					</div>
				</div>
				<div class="col-md-6 col-sm-12">
					<div class="form-floating">
						{{create_user_form.last_name}}
						<label class="text-muted" for="id_last_name"><span class="fw-normal text-dark">Last Name</span>
							<span class="text-danger text-bold">*</span></label>
					</div>
				</div>
			</div>
			<div class="row mt-1 g-3">
				<div class="col text-center">
					<label class="text-danger d-none" id="email_error_label">This Email is Already Registered</label>
					<div class="form-floating">
						{{create_user_form.email}}
						<label class="text-muted" for="id_email"><span class="fw-normal text-dark">Email address</span>
							<span class="text-danger text-bold">*</span></label>
					</div>
				</div>
			</div>

			<div class="row g-3 mt-2">
				<div class="col-md-6 col-sm-12">
					<div class="form-floating">
						{{create_user_form.country_code}}
						<label class="text-muted" for="id_country_code"> <span class="fw-normal text-dark">
								Country Code</span> <span class="text-danger text-bold">*</span>
						</label>
					</div>
				</div>
				<div class="col-md-6 col-sm-12">
					<div class="form-floating">
						{{create_user_form.phone}}
						<label class="text-muted" for="id_phone"><span class="fw-normal text-dark">Mobile Phone
								Number</span>
							<span class="text-danger text-bold">*</span></label>
					</div>
				</div>
			</div>

			<div class="row mt-3">
				<div class="col text-start">
					<a href="{% url 'login' %}" class="btn btn-small" type="button"><i
							class="fa-solid fa-chevron-left"></i> Sign In</a>
				</div>
				<div class="col text-end">
					<button class="btn btn-small " type="button" data-next-button>Next <i
							class="fa-solid fa-chevron-right"></i></button>
				</div>
			</div>
		</div>
		<!-- 3 : Password -->
		<div class="form-page d-none w-100">
			<div class="row">
				<div class="col-12 text-center text-dark">
					<h3>Choose a password</h3>
				</div>
			</div>
			<div class="row g-3 mt-1">
				<div class="col-sm-12">
					<div class="form-floating">
						{{create_user_form.password1}}
						<label class="text-muted" for="id_password1"><span class="fw-normal text-dark">Password</span>
							<span class="text-danger text-bold">*</span></label>
					</div>
				</div>
			</div>
			<div class="row g-3 d-none" id="password-container">
				<div class="alert alert-danger alert-dismissible col-12" role="alert">
					<ul class="list-group list-group-flush" id="password-list">
					</ul>
				</div>
			</div>
			<div class="row mt-3">
				<div class="col-sm-12">
					<label class="text-danger d-none" id="password2_error_label">Passwords Must Match</label>
					<div class="form-floating">
						{{create_user_form.password2}}
						<label class="text-muted" for="id_password2"><span class="fw-normal text-dark">Password
								Confirmation</span> <span class="text-danger text-bold">*</span></label>
					</div>
				</div>
			</div>
			<div class="row mt-3">
				<div class="col text-start">
					<button class="btn btn-small" type="button" data-previous-button><i
							class="fa-solid fa-chevron-left"></i> Prev</button>
				</div>
				<div class="col text-end">
					<button class="btn btn-small " type="button" data-next-button>Next <i
							class="fa-solid fa-chevron-right"></i></button>
				</div>
			</div>
		</div>
		{{create_user_form.age.as_hidden}}
		{{create_hacker_form}}
		<!-- 4 : Agreements -->
		<div class="form-page d-none" id="formSubmission">
			<div class="row">
				<div class="col-12 text-center text-dark">
					<h3>Agreements</h3>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="form-check mt-3">
						<input class="form-check-input req-input" type="checkbox" onclick="formSubmission()" required
							value="" id="codeOfConduct">
						<label class="form-check-label text-dark" for="codeOfConduct">
							I have read and agree to the <a href="{% url 'conduct' %}" target="_blank"
								rel="noopener noreferrer">Code of Conduct</a>.
						</label>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="form-check mt-3">
						<input class="form-check-input req-input" type="checkbox" onclick="formSubmission()" required
							value="" id="termsConditionsPrivacy">
						<label class="form-check-label text-dark" for="termsConditionsPrivacy">
							I authorize you to share my application/registration information with Christmas Challenge
							organizers, Parkyeri
							for event administration, ranking, and administration in-line with the <a
								href="{% url 'privacy' %}" target="_blank" rel="noopener noreferrer">Parkyeri's Privacy
								Policy
							</a>. I further agree to the<a href="{% url 'rules' %}" target="_blank"
								rel="noopener noreferrer"> Christmas Challenge Rules</a>.
						</label>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="form-check mt-3 d-none" id="date-check">
						<input class="form-check-input req-input" type="checkbox" onclick="formSubmission()" value=""
							id="date">
						<label class="form-check-label text-dark" for="date">
							I understand that my age (being younger than 18) requires me to bring a <a
								href="{% url 'minor_waiver' %}" target="_blank" rel="noopener noreferrer">minor waiver
								form</a> signed by my primary care taker(s) and my entry will be denied without it. (You
							will receive it via email).
						</label>
					</div>
				</div>
			</div>
			<div class="row mt-3">
				<div class="col text-start">
					<button class="btn btn-small" type="button" data-previous-button> <i
							class="fa-solid fa-chevron-left"></i> Prev</button>
				</div>
				<div class="col text-end">
					<input type="submit" class="btn btn-small" id="submissionButton" value="Register" disabled>
				</div>
			</div>
		</div>
		<div class="row d-none" id="error-reminder-container">
			<div class="col text-center">
				<p class="text-danger ">Please Make Sure All * Fields Are Filled In</p>
			</div>
		</div>
	</div>
</form>
<br>
<p class="text-dark">If you are experiencing any difficulties while registering, please contact the team:
	<a class="form-contact-link text-dark" href="mailto:challenge@parkyeri.com">challenge@parkyeri.com</a>
</p>
{% endblock form %}
{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">
	$(function () {
		$('#datepicker').datepicker("setDate", new Date("1/1/2005"));
	});
</script>
{% endblock %}